name: chat_app
version: 0.1.0
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.1 <4.0.0'

dependencies: 
  firebase_core: ^2.13.0
  image_picker: ^0.8.7+5
  firebase_storage: ^11.2.1
  cloud_firestore: ^4.7.1
  firebase_auth: ^4.6.1
  lottie: ^2.3.2
  introduction_screen: ^3.1.8
  get_storage: ^2.1.1
  google_sign_in: ^6.1.1
  avatar_glow: ^2.0.2
  intl: ^0.18.1
  emoji_picker_flutter: ^1.5.4
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter_icons: 
  android: launcher_icon
  image_path: assets/logo/icon.png
  ios: true

flutter: 
  assets: 
    - assets/lottie/
    - assets/logo/
  uses-material-design: true

