// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzG9uWxeOHfFdVnmrTTZ6ltER7Wj3L7dk',
    appId: '1:368094864012:android:1a8b8a7242052b4d2791a9',
    messagingSenderId: '368094864012',
    projectId: 'chat-telyu',
    storageBucket: 'chat-telyu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNTRXEG1LOi1aBPdtDUMDXDlsbLeqeelw',
    appId: '1:368094864012:ios:ba1e0893c134fd432791a9',
    messagingSenderId: '368094864012',
    projectId: 'chat-telyu',
    storageBucket: 'chat-telyu.appspot.com',
    androidClientId: '368094864012-fi479dvm5jbdg3i7thsf15o8pipbqgid.apps.googleusercontent.com',
    iosClientId: '368094864012-8rhvd1qp4mbjep82ukagtn07d6hinb6e.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
